### PR TITLE
Make general channels multi-language and show rank in defense channels.

### PR DESCRIPTION
**Pull request by brotalnia**
This was merged, but then reverted for unknown reasons back in April. I have been including it in my repack since then and it works great, so i am resubmitting it. All credit goes to Neo2003.

- Fix players with localized clients not being able to see default channels.
- Display player's rank in defense channels.
- Restrict the defense channels based on rank.

Currently if you use a Non-English client you can't see what people write in the default channels like General, nor can they see what you write. Neo's changes resolve the issue and make the chat channels work properly for all clients.

### CODE REVIEW

**Comment by thepparker** [comment]
It was reverted due to significant performance issues

**Comment by fgsfdss** [comment]
Any source for the rank restriction? I believe all players can see the channels (as suggested by http://wowwiki.wikia.com/wiki/Chat?oldid=292879), but speaking in WorldDefense is rank 11 as per http://wowwiki.wikia.com/wiki/Patch_1.6.0. I could not find evidence of LocalDefense being restricted to rank 9, or viewing being restricted to any rank.

**Comment by brotalnia** [comment]
@fgsfdss You could be right, this can be easily changed.

@thepparker Most of the problematic live server updates Elysium has had in the past were because servers weren't updated often enough and update days involved a hundred new commits or more being pushed at the same time, which then resulted in a revert train of a dozen different things. It ought to be tested individually so it can be determined for sure that this causes performance issues, not one of the dozen other commits reverted at the same time. If there is indeed an issue then its better to try fix it, or alternatively reimplement the things it fixes in another way, instead of discarding everything and pretending the issues it fixed don't exist. All of those things are not currently working :/

**Comment by thepparker** [comment]
While there have been some tumultuous releases, this particular commit was reverted not only once, but twice for performance issues. Therefore, pending a complete rewrite of the approach it will not be merged.

**Pull request closed without merging**
