### PR TITLE
Fix to Maexxna's Web Spray

### PR DESCRIPTION
**Pull request by GuybrushGit**
Fixes https://github.com/LightsHope/server/issues/348

The IsImmuneToDamage function wasn't always checking for SPELL_ATTR_UNAFFECTED_BY_INVULNERABILITY and SPELL_ATTR_EX_UNAFFECTED_BY_SCHOOL_IMMUNE.

With this fix Web Spray will properly go through DS and not DI. 
It will also go through Petrification which according to sources is incorrect, Flask of Petrification should make you immune to the web. Not sure what makes Petrification different since its essentially the same immunity as DS, it could be the SPELL_EFFECT_SANCTUARY effect which is only used by Petrification, DI and Vanish.
Any suggestions?

### CODE REVIEW

**Comment by Fiskehatt** [comment]
https://veterans.org.uk/threads/naxxramas-naxx-maexxna.4039/ states that Vanish should work as well:

>WRONG! Rogues can avoid it by vanishing at the right time, I did it twice last night.

>It has been witnessed that with surgical timing Rogues (using Vanish) and Mages (with Iceblock) can avoid the Web Spray and continue to DPS her down during the final Web Spray when they would normally be immobilised. 

This should explain why Petrification is different from DS.

**Comment by GuybrushGit** [comment]
Doesn't explain Ice Block though, Block is pretty much the same as Divine Shield.

**Comment by theloras** [comment]
Vanish does work - see the video below where a player actually macros for Rogues to use it:

"VANISH NOW"

**World of Warcraft - Scion vs. Maexxna (2006)**
In 2006, Scion Guild of Khadgar (US) was the first guild to take out Maexxna only days after killing Grand Widow Faerlina.
https://youtu.be/ceDs09D6iO8?t=95

**Comment by Fiskehatt** [comment]
Hmm, maybe just spells with SPELL_EFFECT_SANCTUARY (Vanish, DI and Petrification) grant immunity to Web spray? That would be quite consistent with all the videos and evidence. The video posted on the issue shows the spray go through Iceblock, whereas the video by theloras shows it can be avoided with Vanish:

https://www.youtube.com/watch?v=LDEP14-uCAs&feature=youtu.be&t=191

Alternatively, the avoidance is somehow related to timing as mentioned in the comment I posted.

**Comment by Slicy** [comment]
Just leaving this here in case it might have any purpose for testing/fixing : the Sanctuary spell effect  granted by Vanish and others should also allow to bypass C'thun's Dark Glare. Try at your own risks.

**Comment by GuybrushGit** [comment]
Copied over from TrinityCore the spell delay check for sanctuary. 
This makes it so with precise timing Vanish can prevent Web Spray.

Web Spray was also incorrectly hitting wrapped players, added a custom rule to the target selection to prevent this and included Petrification.

**Comment by theloras** [comment]
just wondering if there was any other spell/ability that has SPELL_EFFECT_SANCTUARY associated with it that hasn't already been accounted for (ie: Vanish, Flask of Petrification or Divine Intervention)?

**Pull request merged**
