### PR TITLE
Revert Empyrean Demolisher proc rate to default value

### PR DESCRIPTION
**Pull request by GuybrushGit**
The previous change to this proc rate was based only on the TBC proc rate of another weapon that shared the same proc spell.
Reverting this back to default in the absence of any valid vanilla sources.

### CODE REVIEW

**Comment by ohganot** [comment]
Vanilla source: https://web.archive.org/web/20060516095122/http://www.warriorguideswow.com/index2.php?option=com_content&do_pdf=1&id=13

Quoted as procs every 15 attacks from a vanilla fury warrior who makes guides. One proc every 15 attacks is 6.66% proc chance, while 1.5 PPM would be 7% proc chance. 
This is also supported by the TBC source.

**Comment by n985950** [comment]
> Weapons - Empyrean Demolisher (Or Eskhandar's Right Claw) & Deathbringer // Earthsaker
In my opinion this is BY FAR the best main hand (excluding above) for a fury warrior. Its nice and
slow and the proc is a god send. It stacks with flurry and seems to go off all the time. I'd say the proc rate is 1/15 swings.

lmao dude get out

**Comment by GuybrushGit** [comment]
That source is only stating what he "felt" the proc was, there is no research behind it.

**Comment by InaneHub** [comment]
A lot of these changes makes you wonder if the devs actually read the "proof" before accepting it, this is just ridiculous, like the IF nerf and weapon skill change. I don't know what else to say.

> I'd say the proc rate is 1/15 swings.

This is the extent of the proof

**Comment by ohganot** [comment]
Are you even aware how hard it is to find reliable sources for vanilla? So much has been lost to time.

If you didn't make changes based on minimal evidence, you would have so much more bugs. Alot of the changes are guesswork and approximation.

That is not the extent of the proof I provided. Perhaps you should read the actual report before blaming the developers. It was supported by that comment from vanilla and the fact that the exact same spell id was reused for Dragonstrike in TBC which had 1.5 PPM. Minimal evidence is better than no evidence.

That being said, I'm fine with reverting it if this is their decision.

**Comment by n985950** [comment]
I'd say your evidence is 1/15

**Comment by Retbull** [comment]
Do we need to set up a suicide watch?

**Comment by agrom1** [comment]
just rank to 14 steppenwolf

**Comment by pklnkl** [comment]
"Are you even aware how hard it is to find reliable sources for vanilla? So much has been lost to time."
@ohganot there being a lack of quality information is not a valid reason to justify using poor and low quality evidence to change game stats.  
In vanilla wow there was a ton of things running on circa 5-10% proc rates which you'd see forum posts regularly complaining about being broken with statements such as 'nerf xyz item, it seems to proc every 2 swings and I always die'.  By your logic evidence of this standard is sufficient to justify changing a proc from for example 5% to 50%.  Thats just ridiculous.  There has to be a certain level of quality in evidence presented, a swing test with 1000 swings being subject to statistical error is one thing potentially worthy of discussion, someone just saying a proc is about 1 in 15 swings with no evidence whatsoever to back it up is another completely.

**Comment by pklnkl** [comment]
"Are you even aware how hard it is to find reliable sources for vanilla? So much has been lost to time."
@ohganot  we still need to have evidence that meets a certain standard to justify a change.  There being no higher quality evidence to go on shouldnt mean we make changes off the back of bad or low quality evidence. If anything we should revert to the original value, or even more sensibly select an appropriate proc rate that balances the weapon's damage in line with others of the same/similar item level.

**Comment by Vanillaforprez** [comment]
I applaud the devs for taking the time to double check this. Gives old guys like me hope.

**Comment by phillipnavarro** [comment]
Not going to say anything about the items or legitimacy of certain proc rates over others but I hope devs realize that these constants they juggle around so carelessly are what people base their gearing decisions around. A 6% Empyrean means Kazzak needs to be camped by a guild. A 6% Ironfoe means that rank 14 is not necessary to grind so it is okay to stop at rank 12. A 0.5ppm change motivates or invalidates thousands of hours of playtime. Strange though that evidence is demanded for these points while there is mountains of evidence as to which pvp sets were available at what times yet PvPers are getting their sets early.

**Comment by ohganot** [comment]
Fair enough. Will be interesting to find out in Classic what the actual proc rates were.

**Comment by thepparker** [comment]
Given the evidence required to change the Ironfoe proc rate, and the lack thereof for the Empyrean change (only real motivator was that it shared an identical spell with a weapon from TBC with a well documented rate), we'll be reverting the change to ED. Ironfoe will remain as-is.

**Pull request merged**
