### PR TITLE
Increase visibility range of AQ gate. Closes #151

### LINKED ISSUE #151: AQ gate visibility range
Currently the AQ gate has a low visibility range on the Test realm
https://i.imgur.com/VcXup8o.png

### PR DESCRIPTION
**Pull request by LHGemt**
Closes #151

### CODE REVIEW

**Comment by Kittnz** [comment]
You will have to add GO_AQ_GHOST_GATE = 180322 too

**Comment by thepparker** [comment]
^

**Comment by R3dAlex** [comment]
There is no property called "visibilitymod" in that table...

**Comment by thepparker** [comment]
Yes there is. Make sure you've run all migrations.

**Comment by LHGemt** [comment]
the gost gate did not seem to be visible when I checked it out, so thought it irrelevant. Is that wrong?

**Comment by Kittnz** [comment]
can't see it, but it's there

**Comment by LHGemt** [comment]
That's my point. Is there any reason to increase the visibility range of an invisible object?

**Comment by Kittnz** [comment]
Only reason i can think is if they speed thru or lag out, and it didn't load those objects far away it will let them go through the gate.

**Comment by thepparker** [comment]
I'm going to include these changes in my AQ War Effort patch

**Pull request closed without merging**
