### PR TITLE
The Gates of Ahn'Qiraj War Effort

### PR DESCRIPTION
**Pull request by thepparker**
This PR contains a significant rework of the War Effort handling, from collection, to gong ringing, to the battle.

- Nefarion's shard timer is now Blizzlike (5 hours)
- Long Forgotten Memories will correctly complete at the Crystalline Tear
- The War Effort event now progresses automatically from start to finish
- Resolved a number of typos
- Corrected the availability of some 1.9 items, including some required for the Scepter chain
- War effort resource stacks will now appear and increase in size during the collection event
- War effort resource stacks will now decrease in size while materiels are being moved to Silithus
- Removed a SHITLOAD of custom, hardcoded, NPC gossip menus and texts. They are now using the proper gossips with world states for the current collection values. Some are missing, such as a few of the Horde collector NPC gossips when their collection has finished. Pending the availability of some data from retail, I will likely add custom texts based on the Alliance and the few Horde versions that we have.
- The Scarab Gong (and the final part of the Scepter chain) is now only available once the event has moved to Silithus, and will despawn 10 hours after the first bang along with the war. Any number of players may bang the gong while it is up.
- Field Duty quests and AQ20 gear quests from Cenarion Hold are now only available once the war has been completed
- Increased the draw distance of the AQ gate elements and the gong - so even if the zone has low draw distance, players will be able to see the major components
- Rajaxx no longer spawns as a creature that can be engaged during the event. He will appear on top of the gate, perform his yell, and remain there until the end of the battle.
- Implemented a number of missing Colossal Anubisath spawns during the battle. These include several around the gate at the start, and around a dozen along the path to Cenarion Hold
- Implemented the battle sequences
- Implemented Cenarion Hold wave sequence ~4 hours into the battle, lasting around 3 hours.
- Implemented the final battle sequence and associated roleplay, ~4 hours after the Cenarion Hold attack. High Overlord Saurfang will command the armies of Horde and Alliance to march on The Gates of Ahn'Qiraj
- Added many additional Qiraji warrior spawns around the gate during the final battle event, which lasts 2 hours. At this point, the battle ends.
- Corrected the scaling of Resonating Crystal Formations (they need to be huge!)
- Resonating Crystal Formations no longer have a Herbalism tooltip
- Hive Colossus are now active and have increased draw distance to reflect their immense size
- Implemented reward quest (event) triggering on Hive Colossus death
- Implemented AI for Horde and Alliance infantry to enable battle sequence movements
- Added mounts for Orgrimmar, Ironforge and Stormwind Cavalrymen
- Fixed missing equipment on Stormwind Infantry
- Implemented a system for automatic War Effort collection contributions for cases where servers are lacking the population to complete it in a timely manner
- Corrected the reputation requirement on a few of the Scepter chain quests
- Implemented missing sound effects when the gong is rung and the gate is opening

Additionally, I found a number of core issues during this implementation that have been rectified.
- GameObject::SaveToDB will now preserve negative respawn timers (m_spawnByDefault = false)
- Game objects tied to events with m_spawnByDefault = false will now always be added to their map, rather than leaking memory
- GameObject::Despawn will now preserve m_spawnByDefault = false
- Creatures without the flag UNIT_NPC_FLAG_QUESTGIVER will no longer show players their available quests, if any, when spoken to
- Game events started during the current update will no longer disable themselves instantly
- Corrected an issue allowing AutoStoreLoot to bypass loot template conditions

New features added:
- Hard coded game events may now implement a method to control event update timers
- Area trigger teleports may now specify conditions for team, PVP rank and active (or unactive) events. (removed hardcoded handling for Champion/Legend halls)

TODO:
- [x] Horde NPC gossip
- [x] Check through the Scepter chain again
- [x] Check over all turn in quests for the correct repeat rewards
- [x] Enable area triggers for AQ raids once the gate has opened
- [x] Remove Herbalism tooltip on Resonating Crystal Formations
- [x] Gate opening sound effects

Known missing gossips:
- There are gossips for indicating which factions have/have not completed the effort, as well as many for indicating how long until the effort arrives in Silithus. While we know the texts, it is nearly impossible to know which NPCs these belong to. Therefore, I have opted to add some to each recruiter in the capital cities.
- There are random texts about the appearance of Qiraji throughout Silithus and other zones, but again it is unknown who they belong to

### CODE REVIEW

**Comment by Slicy** [comment]
Just a suggestion : you can add to the "TO DO" part 'Sound effect of the gate opening to be added'.
I have no idea what causes it to not happen, but it did not on Anathema.

**Comment by GuybrushGit** [comment]
Probably because no one ever implemented them:

7114 | Ahn_Qiraj_DoorRootsOpen
7115 | Ahn_QiraJ_DoorPlugOpen
7116 | Ahn_Qiraj_DoorRunesOpen

**Comment by thepparker** [comment]
I wasn't even aware they existed. Will add

**Comment by LHGemt** [comment]
The quest [The Nightmare Manifests](http://db.vanillagaming.org/?quest=8736) still has a tendency to not complete. I had a quick look over the script yesterday and it's a big mess, but it might be an idea to add the quest completion to a timer, starting when Eranikus is defeated, so it will complete even when something goes wrong in the many states the event cycles through before the completion currently happens.

**Comment by brotalnia** [comment]
About the gossips, i think the broadcast text table contains gossip texts as well, so you should try looking them up in there if you know what the texts are about. Just use some keyword they may contain like this:
`SELECT * FROM broadcast_text WHERE MaleText LIKE "%something%"`

**Comment by fgsfdss** [comment]
I recall this issue on the quest chain: https://github.com/elysium-project/server/issues/2827

It wasn't brought over here, so just as a reminder.

**Pull request merged**
