### PR TITLE
Removed Warchief cooldown

### PR DESCRIPTION
**Pull request by GuybrushGit**
https://github.com/LightsHope/server/issues/112

Removed cooldown from the Blessing event to keep it consistent with the other world buffs. 
Its still unclear how long the cooldown should be or if there even was a cooldown. Dragonslayer not popping could be a result of a bug and not a cooldown, fixed in 1.7:
>Fixed a bug that was preventing Rallying Cry of the Dragon Slayer to fire when Onyxia's head was turned in (assuming a head was not already up).

Removing all cooldowns seems like the best solution.

### CODE REVIEW

**Comment by knasen88** [comment]
what does this travic ci mean?

**Comment by some2** [comment]
> what does this travic ci mean?

> The job exceeded the maximum time limit for jobs, and has been terminated.

So this error is not pull request related, see https://docs.travis-ci.com/user/customizing-the-build#Build-Timeouts

**Comment by knasen88** [comment]
HELLO YOU IMPLEMENTED TONS OF FUCKING FIXES BUT NOT THIS ONE?

PATCH 
THE
GODDAMN
BUFF
ITS
1 
LINE

**Comment by knasen88** [comment]
@GuybrushGit

**Comment by knasen88** [comment]
please

**Comment by knasen88** [comment]
another week another week of ignoring.
nice
REALLY nice.

**Comment by Omarthegreatone** [comment]
Ignoring horde mechanics? I'm shocked.

**Comment by karatequin** [comment]
Really sad to see this not implemented yet, or Ony buff /nefarian buff being put on the same Cooldown. seems awfully biased to have different development on similar buffs like this.

**Comment by LEGAZIZ** [comment]
Update on this please? Either remove WCB cooldown or add a cooldown for Ony/Nef buff for consistency.

**Comment by Octadoor** [comment]
I want this fix.

All tryhard guilds on horde get WCB for their raids. 
Why should it be, that we have to sit and wait several hours and calculate the next uptime for this buff and change our daily schedule for this? It's super inconvenient

**Comment by thepparker** [comment]
No one is forcing you to wait around for the buff. You don't HAVE to sit and wait, you choose to. There is a bug where the cooldown does not tick when Thrall is not loaded in the grid - this will be fixed.

To compare the Dragonslayer and ZG buffs to WCB is silly. WCB is a faction specific buff that, aside from convoluted means, is only available to Horde. The other two are available for everyone. You cry that the others do not have a cooldown, yet complain about waiting around - you want to wait around for all three as well? The logic here is puzzling, though I do realise it is a poor attempt at trying to force our hand given the backlash that'd be face if we introduced cooldowns on them ;)

Granted the 6 hour cooldown is excessive and doesn't really have any basis behind it, due to the nature of the buff it isn't exactly fair to leave it unlimited like the raid buffs are. We are toying with a 1 hour cooldown, which will make it much more accessible and reliable to acquire, but prevent certain abuse .

**Comment by brotalnia** [comment]
To avoid having to make Thrall an active object, how about we store the unix time when the buff is used, and then just check if a hour has passes since then whenever the quest is turned in? This seems a lot more efficient to me.

**Comment by knasen88** [comment]
But why would you give WCB a hour CD if onyxia/nefarian CD was removed back on nost because of non blizzlike population? No CD is the only viable answer.

And if you're even remotely competitive  you NEED this buff, it's exactly the same as having ony/nef on a one hour CD. I'm sure you saw progress attempted speedrun and even THEY had WCB buff. Saying you don't need to camp around for a buff is stupid logic. You don't have to pop a onyxia head aswell but you damn well do everyweek before raiding.

to me it looks like Alliance devs not giving a single shit about hordes and actively want them worse off as competitors

**Comment by LHplayer** [comment]
@thepparker yes, we HAVE to camp this atrocious world buff to stay competitive in an raiding environment.

**Comment by knasen88** [comment]
I don't get because it's a horde buff you can reasonably slap on a hour CD as if its nothing. The basis behind that is also zero. Not only that but the event of someone turning in a rend head is way more rare than people getting onyxia heads/nefarian heads. As the same person can get 2 rallying cry times per character while only once for warchief. (at which 90% get's wasted as it is right now)

**Comment by thepparker** [comment]
As I said, you aren't forced to camp for the buff, nor do you necessarily need it. It is your choice, and if your guild requires it then that's on them. From what I am aware of, the cooldowns were not necessarily removed on Nostalrius, but rather were never implemented (much akin to most mangos-based servers). Whether that be due to foresight, oversight, or lack of time, we'll never know. Neither WCB, nor Nefarian's head were even implemented back on Nost, so I think we have done more for the Horde players than you accredit us for.

As you say, handing in WCB is rarer than the dragon heads so having a short cooldown will likely not impact it significantly, while still making it much more available than it currently is. Although the buff whorage we witnessed on Anathema during new content releases will not be possible since we are removing buffs during the initial clears, we'd like to avoid scenarios similar to it.

For example, right now the Alliance camp out and pray for a pop and then mind control. If there is no cooldown, they'll be able to pop it with alts whenever, or acquire it significantly faster than they are currently able to. Having a cooldown is just one way to discourage this behaviour.

Since you are already waiting around for the buff, simply having it on a reliable and shorter timer will go a long way to alleviate the situation.

**Comment by knasen88** [comment]
There it comes again >you don't have to get it
that's a bullshit argument don't give me that. Show me proof of ANY guild that clears all of current content that also does not try get worldbuffs at all. They aren't needed afterall, but you WANT them if you can get them. So just stop making it absolute cancer for horde getting them their worldbuffs.

So the cooldown is supposed to be for the Alliance getting it. I highly doubt that because alliance would know the cooldown either way because there are means of cross faction communication in the year of our lord 2017.
And give me a break here, NOBODY in their right mind levels an alt on the opposite faction JUST so they can pop WCB for themselves at appropriate time. Maybe if they bot characters but it's still a long ass haul questline.  And given they then essentially are playing horde, they would KNOW the cooldown and just pop it 5am or whatever when they know it's gonna pop and nobody is around.

The only real way to discourage WCB for alliance players is to simply not make it work. There is no proof that they even should be able to get it in the first place. Now I don't care about them but if you intend to put a cooldown it for the sake of discouraging Alliance you are mistaken, the autists that go for WCB won't be stopped that easily. 
But hey I have provided proof that as long as a head of either dragon is up that buff cannot fire again until it has despawned but that is selectively IGNORED while WCB gets a cooldown because YOU say so. Maybe cooldown on rallying cry would discourage this buff whoring you mentioned? You can start with a random counter between 6 and 9 hours to begin with.

**Comment by LHplayer** [comment]
yes, you are forced to camp the buff to be competitive, what are you on about.. it's like saying you dont need pro-gear to perform in a pro-sport, of course you do. do you think zlatan would perform with sandals in a pro football game? cause that's how it feels playing without wcb as a fury warrior

**Comment by Omarthegreatone** [comment]
Maybe make it bannable to get it as alliance?  And remove cd? But I  guess thepparker is an alliance main, and dont want to be forced to get wcb? Seems like it lol

**Comment by Sylvestersnr** [comment]
@thepparker Is it not allowed for Alliance to get the WCB buff, if you are trying to discourage it? What's the purpose behind trying to discourage it?
In the case of it not being allowed, I don't see why multiple high ranking players haven't been banned.
And if it's in the case of it is allowed, I don't see the problem? Why would you discourage something that is allowed?
You aren't making any sense.

**Comment by thepparker** [comment]
Alliance players are allowed to get WCB if they like, there are no rules against it. The methods used and the lengths these players go to in order to acquire it is something that I personally disagree with, it is clearly an abuse of game design despite being clever use of game mechanics. If you want to camp out for it, feel free.

This is not a personal vendetta against Horde or Alliance, I am merely sharing my thoughts on the matter. Whether you agree with them or not is beside the point. I've already said the 6h cooldown will be changed, you just don't like one of the options I gave.

I am very aware that players will acquire buffs that are available, that doesn't make them a necessity. Even if there is no cooldown, you are still going to be approaching it the same way - wait for the buff, and logout. If people aren't leveling alts for it, or holding it on their alt, you're never going to have it reliably anyway.

Any decision we come to is one made by multiple people, not just myself. Regardless of how you may feel about it, we do decide how features are implemented when taking into account our population. With that said, you'll know what we decide to do once it's included in the patch notes.

PS. I liked the comparison between raiding in Vanilla and professional sports.

**Comment by knasen88** [comment]
But can you goddamn explain your unreasonable 1 hour cooldown on it. NO OTHER BUFF HAS THIS CONDITION.
you are obviously biased because you can't come up with something.

**Comment by Cabro** [comment]
Ony/Nef head buffs had 6 hours CD on retail? What are you talking about?

**Comment by knasen88** [comment]
@Cabro from original bugreport

Patch 1.7 also mentions it briefly that to buff, there can be no (same) head hanging.
https://web.archive.org/web/20070602172347/http://www.worldofwarcraft.com/patchnotes/patch-05-09-13.html

https://github.com/LightsHope/server/issues/112

**Comment by LHplayer** [comment]
don't understand why you would put a cd on it, why should that have a cd but ony doesn't, whats the reasoning behind it, could you please elaborate on the "certain abuse" that would be caused if there was none? like 2h ony duration buffs are popped a lot more regularly and is a hundred times more efficient than wcb for casters while lvling, i can't see any valid abusage of it

**Comment by Cabro** [comment]
@knasen88 exactly, THAT cooldown on the Rallying Cry buff. It was several hours.

**Comment by knasen88** [comment]
@Cabro Well I am saying on this server no other buff has a CD. Why should this one?

**Comment by Octadoor** [comment]
You've said that you're making the buff be on a 1 hour cooldown. Can you please explain why?

As a competetive horde raider you're gonna have to get this buff. It's a way too big of a dps upgrade not to get. If the cooldown is on 1 hour, sure it will be easier. However that's not gonna prevent horde guilds having to communicate the WCB timer constantly on Discord throughout the day. A 1 hour cooldown helps but it doesn't fix the problem. 

You're saying this is not a horde vs alliance fight, but I don't feel like your arguementation for not removing the buff timer isn't "political". If you feel like removing the buff would favor alliance because it would be easier to level a 60 character and pop WCB whenever they want with mindcontrol cap, I think you're looking at from an alliance perspective. And when you say that "you don't have to get the buff" then you're discouraging competetive horde players, as if we're not as competetive when it comes to speedclears and high numbers.

**Comment by LHplayer** [comment]
having it on an 1h cooldown can also be even worse, cause now we will have to spam each other with the cds and eventually ppl will quit doing so because it will be off cd so frequent, you'll gonna have to spend up to an hour only to get this buff when you want it, it just doesnt makes any sense

**Comment by LHplayer** [comment]
thank you so much for this, you are the best

**Pull request merged**
