### PR TITLE
Core/Creature: Add method Creature::DespawnOrUnsummon for despawn tem…

### PR DESCRIPTION
**Pull request by ryancheung**
…porary summons properly(ported from TrinityCore)

### CODE REVIEW

**Comment by brotalnia** [comment]
There are merge conflicts in 2 files. Also please move that #include to the top where the others are placed. And what use does this have btw? There already is ForcedDespawn which supports a delay.

**Comment by ryancheung** [comment]
Conflicts resolved. 

Most of the time, temp summons need to be un-summoned(removed from world). `ForcedDespawn` just despawn the temp summon and the temp summon will respawn eventually.

`Creature::DespawnOrUnsummon` would either deapawn a normal creature or un-summon(remove from world) a temp summon.

**Comment by brotalnia** [comment]
Now the Travis build is failing.

> In file included from /home/travis/build/LightsHope/server/src/game/World.cpp:55:0:
> /home/travis/build/LightsHope/server/src/game/Objects/TemporarySummon.h:48:30: error: ‘void TemporarySummon::UnSummon(uint32)’ cannot be overloaded
>          void MANGOS_DLL_SPEC UnSummon(uint32 msTime);
> /home/travis/build/LightsHope/server/src/game/Objects/TemporarySummon.h:36:30: error: with ‘void TemporarySummon::UnSummon(uint32)’
>          void MANGOS_DLL_SPEC UnSummon(uint32 delayDespawnTime = 0);

**Comment by ryancheung** [comment]
Just notice gemt had implemented time delayed Unsummon already. Commited updated.

**Pull request merged**
