### PR TITLE
Implement Creature Spells system.

### PR DESCRIPTION
**Pull request by brotalnia**
Based on the screenshot of Blizzard's creature editor it appears they had a table that contained sets of spells that creatures using it would cast. Spells that need to be cast on a timer should be implemented this way, instead of casting them from the script of the creature.

Links to the screenshots of blizzard's editor:
https://static.mmo-champion.com/mmoc/images/news/2009/august/raidsdungeons_021.jpg
https://static.mmo-champion.com/mmoc/images/news/2009/august/raidsdungeons_020.jpg

We already had a table named `creature_spells`, but it was always empty, it was part of some specific AI class made by somebody at Nostalrius, which i don't think is assigned to any creatures either. I commented out the unused code and have repurposed the table.

Structure of `creature_spells`:
`entry` - The id for this spells template. Use the creature id and add a 0 at the end so that we can have multiple per creature.
`name` - Plain text name for this template. They had names on Blizzard's side, so i added names too, makes it easier to tell what each entry is for. Name should consist of the Zone Name - Creature Name and any additional info after that. Example from the screenshot "Onyxia's Lair - Onyxia Start".
`spellId` - The id of the spell.
`probability` - The chance to cast the spell from 1 to 100.
`castTarget` - This decides on what target it will be cast. Check the Target enum in CreatureAI.h (moved there from EventAI).
`castFlags` - These are cast flags, same as in EventAI.
`delayInitialMin\Max` - The initial delay before casting the spell. It will pick a random value between min and max. The timers are in seconds, as can be seen from the screenshot.
`delayRepeatMin\Max` - The delay for all subsequent casts.

I have also added a new column in `creature_template` called `spells_template`, that is the entry of the `creature_spells` template that the creature should use by default. You can change which spells template is used by the creature at any time by calling the SetSpellsTemplate function which is now a member of the base CreatureAI class and thus inherited by all the other AI classes. 

This system works in addition to the creature's AI, you don't need to assign it a specific AI class to use it. Just call DoSpellTemplateCasts from UpdateAI. This is done by default for all creature AI classes, but if you override the base function in your core script then you have to call it yourself obviously.

I've added creature spell templates Varimathas and the Defias Pillager in Moonbrook so you can see how it works.

### CODE REVIEW

**Comment by Ovahlord** [comment]
you might take a look at the Mangos system called "EventAI" or Trinitycore's SmartAI system. Both of them are exactly what you mentoin here an can be ported to some degree to fulfill the exact purpose of what you are trying to do here.

**Comment by brotalnia** [comment]
We already have EventAI, but that is for generic scripting. You can see from the screenshots of Blizzard's tools that they had a separate system called Creature Spells and they assign these spell templates to creatures. My implementation is based on these screenshots from Blizzard. If we design our systems the way they did it would lead to more accurate results. Also if you were to cast the spell on a timed event using EventAI, the timer resets even if the cast fails (no mana for example). The Creature Spells system is designed specifically for timing spell casts, it will keep trying to cast the spell until it succeeds before updating the timers.

**Comment by Ovahlord** [comment]
for that you could simply add an cast flag to the existing eventAI system if it supports cast flags. The SmartAI system of TC does support cast flags and if you implement such an flag you get the same result. for example add an cast fag called "CAST_FLAG_REPEAT_BEFORE_RESCHEDULE"

**Comment by brotalnia** [comment]
My point was not to come up with workarounds for the current scripting system, the point is "Creature Spell templates" were a thing on Blizzard's side. Look at those screenshots i posted. Those are Blizzard's creature editing tools, they were shown during Blizzcon 2009. You can see that they assign them to creature templates and can have multiple spell templates per creature for every phase. Doing phases with EventAI is a pain in the butt, it's much easier just to change the spell template used. You can clearly see in the screenshot that this is what Blizzard did for phases, they have multiple spell templates for Onyxia. This system runs in addition to the scripts, it does not matter if the creature is scripted with EventAI or ScriptedAI or EscortAI or anything else, so it will let us simplify a ton of scripts and remove some completely. And since the point of this project is to emulate Blizzard's vanilla servers, then by definition their way of implementing something is the correct way, as it will yield the closest results to what we are trying to replicate.

**Comment by Kittnz** [comment]
But don't forget, the old ways are not always the best ways of doing it.

**Comment by dagochen** [comment]
EventAI does exactly the same as mentioned in the screenshots from the blizzard UI. I am sure i have already seen an EventAI-Editor which looked similar. 

image

**Comment by brotalnia** [comment]
No it does not. Are you purposefully overlooking the giant differences in implementation? Look at the picture.
template 1

How is EventAI equivalent to a set of spells which is assigned to the creature_template entry? EventAI is an AI class used for database scripting. How can i use EventAI for managing spell casts if my creature is scripted with a core script? I can't, EventAI is a separate AI class, you can't use 2 types of AI for the same creature. The creature_spells system is totally separate thing. It is obvious from these screenshots that Blizzard had a table containing sets of spells with timers, which would then by assigned to the creature_template entry of the creature and could be switched between from the AI script to manage phases. The different spell templates even have names describing by who and when they are used, and Blizzard's editor lets you see what other creatures have the same creature_spells template assigned to them.

**Pull request merged**
