### PR TITLE
Remove mobs ability to actively daze you

### LINKED ISSUE #307: [Database] There are mobs that actively CAST Dazed.
Dazed should be a result of being attacked from behind only.
This spell should never be cast actively by a mob.
You can get dazed from mobs that you are facing.
Example: http://db.vanillagaming.org/?npc=6233
http://wowwiki.wikia.com/wiki/Daze

### PR DESCRIPTION
**Pull request by henkethebenke**
Fixes #307

### CODE REVIEW

**Comment by brotalnia** [comment]
The spells in creature_template are what abilities players can use when mind controlling the creature. Only creatures with TotemAI actually cast the spellid from the creature template.

**Comment by henkethebenke** [comment]
Ok, my bad @brotalnia. So issue #307 is not valid? Or can this be fixed elsewhere?

**Comment by brotalnia** [comment]
You could check `creature_ai_scripts` for the spells, but i doubt they are used.

**Comment by GuybrushGit** [comment]
The spells in creature template are still used if the creature is using the generic spell AI so this fix is good.

**Comment by thepparker** [comment]
As mentioned, this may not cover all cases, but does cover those where generic_spell_ai is used. Checking all the AI scripts can be another PR.

**Pull request merged**
