### PR TITLE
Scripting for LBRS Vaelan

### LINKED ISSUE #144: LBRS Vaelan
Original report by:	Meiji1993

Vaelan in LBRS should appear as an orc raider at first crouching at the edge of the platform, then mind probe you and become vaelan.

Currently both NPCs are there and no script occurs

Source:
https://www.youtube.com/watch?v=FsE6iQ6XQTk

Comment by QAkvastskaft
Source with time stamp: https://youtu.be/FsE6iQ6XQTk?t=173

### PR DESCRIPTION
**Pull request by dimefox**
Fixes #144.

I couldn't see how to make him face the player with the scripting so he just turns around.

### CODE REVIEW

**Comment by brotalnia** [comment]
I think the most correct way of doing this is to have only EVENT_T_OOC_LOS in his EventAI and use ACTION_T_EVENT_SCRIPT in there to start an event script that does the rest. You can do everything in the event script, including facing the player with SCRIPT_COMMAND_TURN_TO.

**Comment by dimefox** [comment]
He did have an existing EventAI that was failing to trigger because the OOC_LOS was set to `nonHostile=0`. Which is why i originally went that route. But i can move the rest to scripting if it's the right place.

Also I'm using SCRIPT_COMMAND_TURN_TO already in the creature_movement_script, but how do I make that target the player that triggered the LOS?

**Comment by brotalnia** [comment]
Don't use a movement script, you need to use an event script. If you call ACTION_T_EVENT_SCRIPT from event EVENT_T_OOC_LOS you can start a script from table `event_scripts` with the invoker of the event (the player) as the target, so you can use SCRIPT_COMMAND_TURN_TO with datalong=0 to face the player.

**Comment by dimefox** [comment]
Cool that worked. Everything is now part of the event script except him updating entry because there wasn't a script command for that.

**Comment by brotalnia** [comment]
Can you do the npc flags change too? You can see in the video that you can't interact with him immediately after he changes entry, only after Vaelan says his last line.

Notice how his mouse cursor changes.
https://youtu.be/FsE6iQ6XQTk?t=3m4s

UPDATE `creature_template` SET `npcflag`=0 WHERE `entry`=10296;

And then add gossip and quest giver flag (total value 3) at the end of the event script with SCRIPT_COMMAND_MODIFY_NPC_FLAGS.

**Comment by dimefox** [comment]
Ok, fixed. Cursor thing was a good catch.

**Comment by brotalnia** [comment]
I found more stuff that wasn't implemented and commited it. He has a rather extensive gossip menu, and he is only supposed to have the quest giver flag if the player has an Unadorned Seal of Ascension. If you talk to him while you have the seal, the gossip is different, and there is another script that plays which adds the quest giver flag at the end.

Here is a video of it.
https://www.youtube.com/watch?v=75ZluW4Ae-g

**Pull request merged**
