### PR TITLE
Windows beep

### PR DESCRIPTION
**Pull request by GuybrushGit**
Adds a startup beep on Windows

### CODE REVIEW

**Comment by thepparker** [comment]
I already have a beep on Windows...

**Comment by GuybrushGit** [comment]
Doesn't work for me on Windows 7.

**Comment by GuybrushGit** [comment]
Probably something wrong with my PC.

**Comment by brotalnia** [comment]
Do you have external speakers/headphones ? Since Windows Vista the beep sound comes from there, the internal PC speaker that beeps when you turn on your computer cannot be used in anything newer than Windows XP.

**Pull request closed without merging**
