### PR TITLE
Fix to Edge of Madness loot tables

### PR DESCRIPTION
**Pull request by GuybrushGit**
https://web.archive.org/web/20060415030206/http://wow.allakhazam.com:80/db/mob.html?wmob=15085
https://web.archive.org/web/20060415030206/http://wow.allakhazam.com:80/db/mob.html?wmob=15084
https://web.archive.org/web/20060415030206/http://wow.allakhazam.com:80/db/mob.html?wmob=15083
https://web.archive.org/web/20060415030206/http://wow.allakhazam.com:80/db/mob.html?wmob=15082

### CODE REVIEW

**Comment by thepparker** [comment]
Hmmm. These loot tables are a bit weird. They are meant to be able to drop one or more of their trinket items, hence we see higher than 100% drop rate, but obviously not guaranteed to always drop that many. 

> Veritas and Friends dropped this guy on Saturday Oct 29th.
>
> Does straight up damage and Nature Damage. Killed him on second attempt.
>
> He dropped the dagger and 3 manes.

Which makes it a bit tricky... I think it's safe to say that at LEAST ONE trinket item always drops. The other two are what we need to worry about. The boss-specific items also only add up to about ~85% chance for each of the bosses. Using a bit of deduction, and if my late night brain is thinking correctly, there should probably be a trinket item in this pool too, at a chance of 15%. That's two of them. A third loot group containing just a trinket item at 25% chance would put us at the 140% chance we see on Allakhazam. This means we have a chance to get 3 trinket items, 2 trinket items and a drop, 1 trinket item and a drop, or just two trinket items.

This is also inline with some other reports of getting only a single trinket item:
> down on kirin tor (france), horde side.
> 
> dropped the 2 hand axe and the blood.
> 
> Not that tough, but aggro is unstable :)  

Therefore, there should be 3 loot groups on the bosses. Two groups of the trinket item, and 1 group which consists of the rare items they are able to drop and a trinket item. The reason we need three groups for the trinkets is that 
a) There are two different drop chances, and
b) We need them to drop separately and not stack. Since they are unique you cannot loot a stack of 2, nor can you split it

So: one trinket group with 100% chance; another trinket group with 25% drop chance; and a loot pool with two boss-specific items (probably split evenly), with a trinket item at 15% chance.

**Comment by GuybrushGit** [comment]
Fixed.

**Comment by thepparker** [comment]
You still need to include the queries for removing the trinket item from the item pools in the migration, right?

**Comment by GuybrushGit** [comment]
Forgot about those, fixed.

**Pull request merged**
