### PR TITLE
Maraudon various fixes

### PR DESCRIPTION
**Pull request by sipertruk**
- Fix Theradrim Guardian script action on death (summoning Shardlings).

- Fix the Larva Spewer and surroundings : re-organize spawns a bit, make it maintain a Spewed Larva alive until it's destroyed by a player.
The Spewed Larva travels to Noxxion's pool if not aggro-ed. Also it drops nothing, gives no exp and can't be skinned.
https://youtu.be/-8e4QbGFkrU?t=206 (it's a 2008 video but should work)
https://youtu.be/ATIkYgXWmk0?t=54
http://www.vranx.com/forums/index.php?topic=5775.0
https://web.archive.org/web/20051107183108/http://thottbot.com:80/?z=106 (search for "larva")

- ~~Implement SCRIPT_COMMAND_SET_INST_DATA/64, I needed a way to reach the script at the last of Spewed Larva's waypoints.~~

- Remove 4 warnings on instance loading, remain 2 warnings for a supposed patrol of 2xSister of Celebrian whose destination is unknown.

- While doing the quest about cleansing vines, now you can't finish the quest on the same vine because the corrupted is removed when the healed is summoned.

- Princess Theradrass is facing Boulder spell's target.
https://youtu.be/W5q0C3Km7_A

- Rotgrip can walk on land and is very fast. https://youtu.be/0Zz_N971uGg?t=430

### CODE REVIEW

**Comment by brotalnia** [comment]
I am doing some refactoring to the db scripts right now, i am going to take out the giant switch case and move each command to a separate function, so wait for me to finish cause there will be conflicts.

**Comment by sipertruk** [comment]
Alright. 
I edited my comment to add the vine fix.

**Comment by brotalnia** [comment]
I've implemented the script commands for setting instance data and I've expanded the functionality a bit. You need to revert your changes to those files to fix the merge conflicts. https://github.com/LightsHope/server/commit/d025b44a64bbead7cd896484127fd20da0c08809

**Comment by sipertruk** [comment]
Tested with the scripting changes, looks like it's working.
I should be done with this pull request.

**Pull request merged**
