### PR TITLE
Update quests 3562, 3563, 3564, 3565 minimum level

### PR DESCRIPTION
**Pull request by Jakobud**
For Horde in Azshara, there are a group of 4 "delivery" quests and 4 follow up "payment to NPC" quests. According to my research, I think that the current database has the minimum level requirements for 3562 set incorrectly:

screenshot_1

Strangely, one of them is minimum requirement of 51 for some reason. That's what made me first suspect a bug here.

After research and @brotalnia 's suggestion, I have made an update that fixed the 3562 quest and changes the minimum level requirement to be in-line with the rest of the quests.

### CODE REVIEW

**Comment by brotalnia** [comment]
I think Allakhazam is wrong.

The WoW Master Guide says all should require 45.
master guide

CMaNGOS-Classic, MaNGOSZero and TrinityDB also have them all at 45. So just 3562 is wrong in ours.

**Comment by Jakobud** [comment]
Oh good call on that. Is that Master Guide online in PDF form somewhere? Never thought to look at that. I will update this to only fix that one quest then.

**Comment by Jakobud** [comment]
Updated SQL and ready for merge.

**Comment by brotalnia** [comment]
Thanks, included it in commit https://github.com/LightsHope/server/commit/a9a0cfce16955be1cc469e08f034e2ec7b2f55f0 to avoid adding extra migration.

**Pull request closed without merging**
