### PR TITLE
Fix to MCed mobs neutral status

### PR DESCRIPTION
**Pull request by GuybrushGit**
Fixes https://github.com/LightsHope/server/issues/171

### CODE REVIEW

**Comment by thepparker** [comment]
What's the difference between having it before that block, and doing inside that block?

**Comment by GuybrushGit** [comment]
It was checking for GetAffectingPlayer (the caster) instead of the target.

**Comment by thepparker** [comment]
Ah, I think I see it. GetAffectingPlayer checks if doing something to the target would affect a player, or a player controlled unit. So technically, they'd be doing the same thing if it were placed slightly later. Testing myself, removing UNIT_FLAG_PVP_ATTACKABLE entirely seems to have no impact on the functionality of MC.

**Comment by GuybrushGit** [comment]
We don't want to remove that flag from a target player though. Looking at the code it gets set on Player::Create and only removed when doing the triage quests.

**Comment by thepparker** [comment]
Sorry, I meant the adding and removing of it. i.e, not setting it (and not clearing it) seems to have no impact

**Comment by GuybrushGit** [comment]
Tested it as well without that flag, found no issues. Commited.

**Pull request merged**
