### PR TITLE
AB reputation tick values

### PR DESCRIPTION
**Pull request by GuybrushGit**
Fixes https://github.com/LightsHope/server/issues/380

### CODE REVIEW

**Comment by brotalnia** [comment]
Hmm, are these values supposed to change from patch to patch? You can use sWorld.GetWowPatch() to do that. Cause i see it says "Progressive" in the comment above.

**Comment by GuybrushGit** [comment]
The source for the mistake could be this wiki article: http://wowwiki.wikia.com/wiki/Battleground_reputation_mobs
It has the wrong values during all the patches.

Video evidence confirms 200 ticks: https://youtu.be/_4mPemLTQdM?t=59

**Comment by thepparker** [comment]
I recall there being mention of a reputation increase or decrease in the patch notes, what the actual value is I don't know

**Comment by GuybrushGit** [comment]
Patch 1.10
>The reputation gain in Warsong Gulch and Arathi Basin has been significantly increased

**Comment by GuybrushGit** [comment]
Pre 1.10 video:
https://youtu.be/gJQ8JR1a6sA?t=54
10 reputation at 1400

**Pull request merged**
