### PR TITLE
Ironfoe procrate should be slightly higher, until patch 1.10

### PR DESCRIPTION
**Pull request by brobot9001**
As we know from #204 , our best test for this proc is a 3k sample preformed in 1.12.1 resulting in a 2.7% chance.
https://web.archive.org/web/20070315172720/http://wow.allakhazam.com/item.html?witem=11684
"After some testing on a Servant mob in the Blasted Lands, I have a more accurate idea of the proc rate."

Lets consider 4%. 
Given the small sample size, 1.3% deviation isn't all that unlikely. Considering that blizzard doesn't use anything lower than 1.0ppm and that 1.0ppm is the default for all procs that seems like clearly the best choice.

However;  #989 makes an important point. Ironfoe is supposed to proc three attacks instead of two until patch 1.10. This is information from vanilla patch notes.
https://wow.gamepedia.com/Ironfoe/Legacy
https://wow.gamepedia.com/Patch_1.10.0

Since we know that blizzard doesn't use procs lower than 1.0 , Ironfoe before 1.10.0 must be at at least 1.0ppm even with the extra swing. This is how it should be on Lightshope in our current patch.

However; After speaking with some devs it is my understanding that modifying the effects attached to spell IDs is a nightmare from the client side of things, so like any other spell, changing the spell effect is not an option.

Therefore to best way to fix this fissure between retail and this project is to set Ironfoe to 1.5ppm until 1.10.0. This procrate give us the closest comparison to having a 1.0ppm proc of three hits in terms of extra hits gained.

### CODE REVIEW

**Comment by dorkyo** [comment]
The only conflicting argument to this is that Ironfoe was nerfed instead in 1.3 and not 1.10.0

The only evidence I can find to destroy that argument is such:

Patch 1.3 release date was March 7th 2005
https://wow.gamepedia.com/Patch_1.3.0

Ironfoe on May 29th 2005 displaying 3 extra attacks.
http://web.archive.org/web/20050529015450/http://wow.allakhazam.com/item.html?witem=11684

If Ironfoe was in fact nerfed in 1.3, and not in 1.10.0 it would not still display three extra attacks in the above snapshot.

Reverting the proc rate nerf until, and only until patch 1.10.0 seems to be the most viable option, if editing the spell effect itself is something not so easily done.

**Comment by druidish** [comment]
Looks like the proc was changed to 2 attacks from 3 in 1.7 going off this link.

"stealth nerf? - Posted by riceless on 2005-09-21 07:48:16"
http://web.archive.org/web/20051003200816/http://thottbot.com:80/?i=23837

**Comment by Pre-Elysium** [comment]
The 1.3.0 nerf I believe was just a bug fix that caused your swing timer to be reset when the proc went off giving you an additional (at the time, a fourth) attack.

Buffing the proc rate to bring IF in line with it's pre 1.10 incarnation does indeed seem a viable solution, however I have no idea where to begin determining equivalence between the proc and an extra attack.

I suppose you could compare the rate to the extra attacks and try to get a proc rate that over the course of a sample size would give an equal number of extra attacks? Seems messy imo

**Comment by ohganot** [comment]
There's no mention of Ironfoe here: http://wowwiki.wikia.com/wiki/Patch_1.10

The 3 attacks was removed earlier, either in patch 1.7 or patch 1.3.

**Comment by Pre-Elysium** [comment]
I think @druidish has it right: 1.7.0 released 13 September 2005, those stealth nerf comments are from 9/21/2005 at the earliest.

Blizzard never released full patch notes, there were thousands of stealth nerfs all the time. This stealth nerf players actually noticed since they had to update the text of Ironfoe. The nerf in 1.3.0 is totally separate and bug related to extra attacks.

I'm not sure about the discrepancy between the wayback comments and https://wow.gamepedia.com/Ironfoe/Legacy however if you look at http://wowwiki.wikia.com/wiki/Ironfoe you see the only time Ironfoe was mentioned officially was for that bug fix

**Comment by QAkvastskaft** [comment]
Closed pending actual source as described in issue #989

**Pull request closed without merging**
